export {default as Landing} from './Landing.jsx'
export {default as Register} from './Registration.jsx'
export {default as Login} from './Login.jsx'
export {default as Main} from "./Customer_main.jsx"
export {default as Delivery} from "./Delivery.jsx"
export {default as CustAcc} from "./CustAcc.jsx"
export {default as Header} from "./Header.jsx"
export {default as Footer} from "./Footer.jsx"
export {default as Dropdown} from "./Dropdown.jsx"
export {default as AdminDash} from "./admin/AdminDash.jsx"
export {default as Content} from "./Main.jsx"
export {default as Modal} from "./Modal.jsx"
export {default as Details} from "./Details.jsx"
export {default as AdSide} from "./admin/AdminSide.jsx"
export {default as CustTable} from "./admin/CustTable.jsx"
export {default as DeliveryTable} from "./admin/DeliveryTable.jsx"
export {default as AdmMain} from "./admin/AdmMain.jsx"
