export {default as Landing} from './Landing.jsx'
export {default as Register} from './Registration.jsx'
export {default as Login} from './Login.jsx'
export {default as Main} from "./Customer_main.jsx"
export {default as Delivery} from "./Delivery.jsx"
export {default as CustAcc} from "./CustAcc.jsx"
export {default as Header} from "./Header.jsx"
export {default as Footer} from "./Footer.jsx"
export {default as Dropdown} from "./Dropdown.jsx"
export {default as AdminDash} from "./AdminDash.jsx"
